apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      volumes:
      - name: db-secrets-vol
        secret:
          secretName: db-secret
      containers:
      - name: backend
        image: rganesh7/backend:v5.1
        ports: 
        - containerPort: 5000
        command: ["python3", "/home/ubuntu/app.py"]
        
        env:
        - name: DB_USER
          value: "admin"
        - name: DB_NAME
          value: "webapp_db"

        volumeMounts:
        - name: db-secrets-vol
          mountPath: "/app/secrets/"
          readOnly: true

---

apiVersion: v1
kind: Service
metadata: 
  name: backend
spec:
  selector:
    app: python-app
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000