apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-success-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: success
  template:
    metadata:
      labels:
        app: success
    spec:
      containers:
      - name: success
        image: rganesh7/frontend-success:v1.0
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: success
spec:
  selector:
    app: success
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80