apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-login-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      # volumes:
      # - name: login-conf-vol
      #   configMap:
      #     name: login-config
      containers:
      - name: login
        image: rganesh7/frontend-login:v1.0
        ports:
        - containerPort: 80
        # volumeMounts:
        # - name: login-conf-vol
        #   mountPath: "/etc/nginx/conf.d"
          # readOnly: true

---

apiVersion: v1
kind: Service
metadata:
  name: login
spec:
  selector:
    app: login
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80